**Q1** Import the numpy package under the name np and Print the numpy version and the configuration 

In [ ]:
import numpy as np
np.version.version

'1.19.5'

2.Create a null vector of size 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3.Create Simple 1-D array and check type and check data types in array

In [ ]:
arr = np.arange(0,7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

4.How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
print(f'No of Dimension of the array : {arr.ndim}')
print(f'Size of the element in the array : {arr.itemsize}')
print(f'Total Size of the array : {arr.nbytes}')

No of Dimension of the array : 1
Size of the element in the array : 8
Total Size of the array : 56


5) Create a null vector of size 10 but the fifth value which is 1

In [ ]:
null_arr = np.zeros(10)
null_arr[4] = 1
print(null_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6) Create a vector with values ranging from 10 to 49

In [ ]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
7) Reverse a vector (first element becomes last)

In [ ]:
print(f'before reversing: {arr}')
print(f'after reversing : {arr[::-1]}')

before reversing: [0 1 2 3 4 5 6]
after reversing : [6 5 4 3 2 1 0]


In [ ]:
8) Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matrix = np.arange(0,9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr1 = [1,2,0,0,4,0]
arr1


[1, 2, 0, 0, 4, 0]

In [ ]:
np.nonzero(arr1)

(array([0, 1, 4]),)

In [ ]:
10) Create a 3x3 identity matrix

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
11) Create a 3x3x3 array with random values

In [ ]:
np.random.random((3,3,3))

array([[[0.13458205, 0.93183481, 0.43871203],
        [0.57112797, 0.72479216, 0.59883513],
        [0.98335182, 0.16584645, 0.16673978]],

       [[0.65043795, 0.30342102, 0.97633225],
        [0.50152324, 0.51456821, 0.2836293 ],
        [0.45482988, 0.42813014, 0.87966258]],

       [[0.31616395, 0.1591692 , 0.93220233],
        [0.25076563, 0.023682  , 0.67222602],
        [0.93898113, 0.19822007, 0.15318595]]])

12) Create a 10x10 array with random values and find the minimum and maximum values


In [ ]:
arr2 = np.random.random((3,3,3))
print(f'array: \n{arr2}')
print(f'Max value in array : \n {np.max(arr2)}')
print(f'Min value in array : \n {np.min(arr2)}')

array: 
[[[0.93003662 0.52783979 0.21688534]
  [0.65904756 0.6470456  0.28823147]
  [0.53792765 0.33825037 0.31650647]]

 [[0.70465913 0.10031179 0.75025692]
  [0.44042377 0.75578587 0.54294015]
  [0.71147147 0.04714615 0.01199767]]

 [[0.76608603 0.87335895 0.70713046]
  [0.49734402 0.21902101 0.69659963]
  [0.09823971 0.97013487 0.22972779]]]
Max value in array : 
 0.9701348694670148
Min value in array : 
 0.011997671299736501


13) Create a random vector of size 30 and find the mean value

In [ ]:
print(f'array :{arr2}')
print(f'mean value o the array:  {np.mean(arr2)} ')

array :[[[0.93003662 0.52783979 0.21688534]
  [0.65904756 0.6470456  0.28823147]
  [0.53792765 0.33825037 0.31650647]]

 [[0.70465913 0.10031179 0.75025692]
  [0.44042377 0.75578587 0.54294015]
  [0.71147147 0.04714615 0.01199767]]

 [[0.76608603 0.87335895 0.70713046]
  [0.49734402 0.21902101 0.69659963]
  [0.09823971 0.97013487 0.22972779]]]
mean value o the array:  0.5031261577082042 


In [ ]:
14) Create a 2d array with 1 on the border and 0 inside

In [ ]:
arr4 = np.ones((5,5))
arr4[1:4,1:4] = 0
arr4

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
15 ) How to add a border (filled with 0's) around an existing array?

In [ ]:
arr5 = np.ones((5,5))
arr5[:1,:] = 0
arr5[4:,:] = 0
arr5[:,:1] = 0
arr5[:,4:] = 0
arr5


array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
16) How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?
Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]
Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [ ]:
arr6 = np.arange(1,15).reshape(2,7)
arr6

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
arr6[1,-2]

13

In [ ]:
arr6[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr6[:,2]

array([ 3, 10])

In [ ]:
arr6[0,1::2]

array([2, 4, 6])

In [ ]:
print(f'Before changing :\n {arr1}')
arr6[1,-2] = 20
print(f'\nAfter changiing :\n {arr1}')

Before changing :
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

After changiing :
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
17) How to Convert a 1D array to a 2D array with 2 rows


In [ ]:
arr8 = np.arange(0,9)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(f'no of dimensions of array : {arr8.ndim}')

no of dimensions of array : 1


In [ ]:
arr8 = arr8.reshape((3,3))
arr8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
print(f'no of dimensions of array : {arr8.ndim}')

no of dimensions of array : 2


In [ ]:
18) Create the following pattern without hardcoding. Use only numpy functions and the below
input array a.
Input:
a = np.array([1,2,3])
Desired Output:
> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3,
1, 2, 3])

In [2]:

import numpy as np
s = np.array([1,2,3])
print(s)

[1 2 3]


In [4]:
import numpy as np
a = np.append(np.repeat(s,3),np.tile(s,3))
print(a)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [ ]:
19) Write a program to show how Numpy taking less memory compared to Python List?

In [5]:
import sys
list1 = range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(list1))
print("Size of the whole list in bytes: ",sys.getsizeof(list1)*len(list1))
# declaring a Numpy array  1000 elements
array = np.arange(1000)
print("\nSize of each element of the Numpy array in bytes: ",array.itemsize)
print("Size of the whole Numpy array in bytes: ",array.size * array.itemsize)


Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000

Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


In [ ]:
20) Write a program to show how Numpy taking less time compared to Python List?

In [6]:
import time
size = 1000000
list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)

initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]
print(f"Time taken by Lists to perform multiplication: {(time.time() - initialTime)} s")
initialTime = time.time()
resultantArray = array1 * array2
print(f"\nTime taken by NumPy Arrays to perform multiplication: {(time.time() - initialTime)} s")

Time taken by Lists to perform multiplication: 0.12133455276489258 s

Time taken by NumPy Arrays to perform multiplication: 0.0031652450561523438 s
